services:
  - type: web
    name: simulator-backend
    runtime: node
    buildCommand: npm ci
    startCommand: npm run start
    port: 5001
    healthCheckPath: /health
    autoDeploy: true
    environment:
       NODE_ENV: production
       DB_NAME: test
       PORT: 5001
       ALLOWED_ORIGINS: https://simulator-olx4.onrender.com,https://simuatech.netlify.app,http://localhost:3000,http://localhost:5173,http://localhost:4173